result_processor 0 8
result_processor 1 8
result_processor 2 8
result_processor 3 8
result_processor 4 8
result_processor 5 8
result_processor 6 8
result_processor 7 8
Processing experiment results. Start: 0 Step: 8
Processing experiment results. Start: 1 Step: 8
Processing experiment results. Start: 2 Step: 8
Processing experiment results. Start: 3 Step: 8
Processing experiment results. Start: 7 Step: 8
Processing experiment results. Start: 5 Step: 8
Processing experiment results. Start: 4 Step: 8
Processing experiment results. Start: 6 Step: 8
0000: analyzing
Analyzing: /root/current-deployment-data/experiment-output/0000
  > Loading trace into database...
python3 scripts/analyze/load-logs.py /root/current-deployment-data/experiment-output/0000/eventDB.sqlite /root/current-deployment-data/experiment-output/0000/slave-*/*.trc
    Events loaded: 46102
  > Loaded trace into database in 0 s.
  > Running queries on trace database: queries/ethereum.sql
  > Processed 'queries/ethereum.sql' in 0 s.
  > Running queries on trace database: queries/aggregates.sql
  > Processed 'queries/aggregates.sql' in 0 s.
  > Running queries on trace database: queries/histograms.sql
Traceback (most recent call last):
  File "/root/scripts/analyze/run-queries.py", line 67, in <module>
    rows = cur.execute(q).fetchall()
sqlite3.OperationalError: table request_truncated already exists
  > Processed 'queries/histograms.sql' in 0 s.
0001: analyzing
Analyzing: /root/current-deployment-data/experiment-output/0001
  > Loading trace into database...
python3 scripts/analyze/load-logs.py /root/current-deployment-data/experiment-output/0001/eventDB.sqlite /root/current-deployment-data/experiment-output/0001/slave-*/*.trc
    Events loaded: 84581
  > Loaded trace into database in 0 s.
  > Running queries on trace database: queries/ethereum.sql
  > Processed 'queries/ethereum.sql' in 0 s.
  > Running queries on trace database: queries/aggregates.sql
  > Processed 'queries/aggregates.sql' in 0 s.
  > Running queries on trace database: queries/histograms.sql
Traceback (most recent call last):
  File "/root/scripts/analyze/run-queries.py", line 67, in <module>
    rows = cur.execute(q).fetchall()
sqlite3.OperationalError: table request_truncated already exists
  > Processed 'queries/histograms.sql' in 0 s.
0002: analyzing
Analyzing: /root/current-deployment-data/experiment-output/0002
  > Loading trace into database...
python3 scripts/analyze/load-logs.py /root/current-deployment-data/experiment-output/0002/eventDB.sqlite /root/current-deployment-data/experiment-output/0002/slave-*/*.trc
    Events loaded: 121459
  > Loaded trace into database in 0 s.
  > Running queries on trace database: queries/ethereum.sql
  > Processed 'queries/ethereum.sql' in 0 s.
  > Running queries on trace database: queries/aggregates.sql
  > Processed 'queries/aggregates.sql' in 0 s.
  > Running queries on trace database: queries/histograms.sql
Traceback (most recent call last):
  File "/root/scripts/analyze/run-queries.py", line 67, in <module>
    rows = cur.execute(q).fetchall()
sqlite3.OperationalError: table request_truncated already exists
  > Processed 'queries/histograms.sql' in 0 s.
0003: analyzing
Analyzing: /root/current-deployment-data/experiment-output/0003
  > Loading trace into database...
python3 scripts/analyze/load-logs.py /root/current-deployment-data/experiment-output/0003/eventDB.sqlite /root/current-deployment-data/experiment-output/0003/slave-*/*.trc
    Events loaded: 160330
  > Loaded trace into database in 0 s.
  > Running queries on trace database: queries/ethereum.sql
  > Processed 'queries/ethereum.sql' in 0 s.
  > Running queries on trace database: queries/aggregates.sql
  > Processed 'queries/aggregates.sql' in 1 s.
  > Running queries on trace database: queries/histograms.sql
Traceback (most recent call last):
  File "/root/scripts/analyze/run-queries.py", line 67, in <module>
    rows = cur.execute(q).fetchall()
sqlite3.OperationalError: table request_truncated already exists
  > Processed 'queries/histograms.sql' in 0 s.
0004: analyzing
Analyzing: /root/current-deployment-data/experiment-output/0004
  > Loading trace into database...
python3 scripts/analyze/load-logs.py /root/current-deployment-data/experiment-output/0004/eventDB.sqlite /root/current-deployment-data/experiment-output/0004/slave-*/*.trc
    Events loaded: 196537
  > Loaded trace into database in 0 s.
  > Running queries on trace database: queries/ethereum.sql
  > Processed 'queries/ethereum.sql' in 0 s.
  > Running queries on trace database: queries/aggregates.sql
  > Processed 'queries/aggregates.sql' in 1 s.
  > Running queries on trace database: queries/histograms.sql
Traceback (most recent call last):
  File "/root/scripts/analyze/run-queries.py", line 67, in <module>
    rows = cur.execute(q).fetchall()
sqlite3.OperationalError: table request_truncated already exists
  > Processed 'queries/histograms.sql' in 0 s.
0005: analyzing
Analyzing: /root/current-deployment-data/experiment-output/0005
  > Loading trace into database...
python3 scripts/analyze/load-logs.py /root/current-deployment-data/experiment-output/0005/eventDB.sqlite /root/current-deployment-data/experiment-output/0005/slave-*/*.trc
    Events loaded: 234614
  > Loaded trace into database in 1 s.
  > Running queries on trace database: queries/ethereum.sql
  > Processed 'queries/ethereum.sql' in 0 s.
  > Running queries on trace database: queries/aggregates.sql
  > Processed 'queries/aggregates.sql' in 1 s.
  > Running queries on trace database: queries/histograms.sql
Traceback (most recent call last):
  File "/root/scripts/analyze/run-queries.py", line 67, in <module>
    rows = cur.execute(q).fetchall()
sqlite3.OperationalError: table request_truncated already exists
  > Processed 'queries/histograms.sql' in 0 s.
0006: analyzing
Analyzing: /root/current-deployment-data/experiment-output/0006
  > Loading trace into database...
python3 scripts/analyze/load-logs.py /root/current-deployment-data/experiment-output/0006/eventDB.sqlite /root/current-deployment-data/experiment-output/0006/slave-*/*.trc
    Events loaded: 272061
  > Loaded trace into database in 1 s.
  > Running queries on trace database: queries/ethereum.sql
  > Processed 'queries/ethereum.sql' in 0 s.
  > Running queries on trace database: queries/aggregates.sql
  > Processed 'queries/aggregates.sql' in 2 s.
  > Running queries on trace database: queries/histograms.sql
Traceback (most recent call last):
  File "/root/scripts/analyze/run-queries.py", line 67, in <module>
    rows = cur.execute(q).fetchall()
sqlite3.OperationalError: table request_truncated already exists
  > Processed 'queries/histograms.sql' in 0 s.
0007: analyzing
Analyzing: /root/current-deployment-data/experiment-output/0007
  > Loading trace into database...
python3 scripts/analyze/load-logs.py /root/current-deployment-data/experiment-output/0007/eventDB.sqlite /root/current-deployment-data/experiment-output/0007/slave-*/*.trc
    Events loaded: 310361
  > Loaded trace into database in 1 s.
  > Running queries on trace database: queries/ethereum.sql
  > Processed 'queries/ethereum.sql' in 0 s.
  > Running queries on trace database: queries/aggregates.sql
  > Processed 'queries/aggregates.sql' in 2 s.
  > Running queries on trace database: queries/histograms.sql
Traceback (most recent call last):
  File "/root/scripts/analyze/run-queries.py", line 67, in <module>
    rows = cur.execute(q).fetchall()
sqlite3.OperationalError: table request_truncated already exists
  > Processed 'queries/histograms.sql' in 0 s.
0008: analyzing
Analyzing: /root/current-deployment-data/experiment-output/0008
  > Loading trace into database...
python3 scripts/analyze/load-logs.py /root/current-deployment-data/experiment-output/0008/eventDB.sqlite /root/current-deployment-data/experiment-output/0008/slave-*/*.trc
    Events loaded: 348088
  > Loaded trace into database in 1 s.
  > Running queries on trace database: queries/ethereum.sql
  > Processed 'queries/ethereum.sql' in 0 s.
  > Running queries on trace database: queries/aggregates.sql
  > Processed 'queries/aggregates.sql' in 2 s.
  > Running queries on trace database: queries/histograms.sql
Traceback (most recent call last):
  File "/root/scripts/analyze/run-queries.py", line 67, in <module>
    rows = cur.execute(q).fetchall()
sqlite3.OperationalError: table request_truncated already exists
  > Processed 'queries/histograms.sql' in 0 s.
Finished processing results. First unprocessed: 10
Finished processing results. First unprocessed: 11
Finished processing results. First unprocessed: 12
0009: analyzing
Analyzing: /root/current-deployment-data/experiment-output/0009
  > Loading trace into database...
python3 scripts/analyze/load-logs.py /root/current-deployment-data/experiment-output/0009/eventDB.sqlite /root/current-deployment-data/experiment-output/0009/slave-*/*.trc
Finished processing results. First unprocessed: 13
Finished processing results. First unprocessed: 14
Finished processing results. First unprocessed: 15
    Events loaded: 387232
  > Loaded trace into database in 1 s.
  > Running queries on trace database: queries/ethereum.sql
  > Processed 'queries/ethereum.sql' in 0 s.
  > Running queries on trace database: queries/aggregates.sql
Finished processing results. First unprocessed: 16
  > Processed 'queries/aggregates.sql' in 2 s.
  > Running queries on trace database: queries/histograms.sql
Traceback (most recent call last):
  File "/root/scripts/analyze/run-queries.py", line 67, in <module>
    rows = cur.execute(q).fetchall()
sqlite3.OperationalError: table request_truncated already exists
  > Processed 'queries/histograms.sql' in 0 s.
Finished processing results. First unprocessed: 17
Finished continuous result analysis.
