result_processor 0 8
result_processor 1 8
result_processor 2 8
result_processor 3 8
result_processor 4 8
result_processor 5 8
result_processor 6 8
result_processor 7 8
Processing experiment results. Start: 0 Step: 8
Processing experiment results. Start: 1 Step: 8
Processing experiment results. Start: 3 Step: 8
Processing experiment results. Start: 2 Step: 8
Processing experiment results. Start: 4 Step: 8
Processing experiment results. Start: 5 Step: 8
Processing experiment results. Start: 6 Step: 8
Processing experiment results. Start: 7 Step: 8
0000: analyzing
Analyzing: /root/current-deployment-data/experiment-output/0000
  > Loading trace into database...
python3 scripts/analyze/load-logs.py /root/current-deployment-data/experiment-output/0000/eventDB.sqlite /root/current-deployment-data/experiment-output/0000/slave-*/*.trc
    Events loaded: 54697
  > Loaded trace into database in 0 s.
  > Running queries on trace database: queries/ethereum.sql
  > Processed 'queries/ethereum.sql' in 0 s.
  > Running queries on trace database: queries/aggregates.sql
  > Processed 'queries/aggregates.sql' in 0 s.
  > Running queries on trace database: queries/histograms.sql
Traceback (most recent call last):
  File "/root/scripts/analyze/run-queries.py", line 67, in <module>
    rows = cur.execute(q).fetchall()
sqlite3.OperationalError: table request_truncated already exists
  > Processed 'queries/histograms.sql' in 0 s.
0001: analyzing
Analyzing: /root/current-deployment-data/experiment-output/0001
  > Loading trace into database...
python3 scripts/analyze/load-logs.py /root/current-deployment-data/experiment-output/0001/eventDB.sqlite /root/current-deployment-data/experiment-output/0001/slave-*/*.trc
    Events loaded: 54711
  > Loaded trace into database in 0 s.
  > Running queries on trace database: queries/ethereum.sql
  > Processed 'queries/ethereum.sql' in 0 s.
  > Running queries on trace database: queries/aggregates.sql
  > Processed 'queries/aggregates.sql' in 0 s.
  > Running queries on trace database: queries/histograms.sql
Traceback (most recent call last):
  File "/root/scripts/analyze/run-queries.py", line 67, in <module>
    rows = cur.execute(q).fetchall()
sqlite3.OperationalError: table request_truncated already exists
  > Processed 'queries/histograms.sql' in 0 s.
0002: analyzing
Analyzing: /root/current-deployment-data/experiment-output/0002
  > Loading trace into database...
python3 scripts/analyze/load-logs.py /root/current-deployment-data/experiment-output/0002/eventDB.sqlite /root/current-deployment-data/experiment-output/0002/slave-*/*.trc
    Events loaded: 54885
  > Loaded trace into database in 0 s.
  > Running queries on trace database: queries/ethereum.sql
  > Processed 'queries/ethereum.sql' in 0 s.
  > Running queries on trace database: queries/aggregates.sql
  > Processed 'queries/aggregates.sql' in 0 s.
  > Running queries on trace database: queries/histograms.sql
Traceback (most recent call last):
  File "/root/scripts/analyze/run-queries.py", line 67, in <module>
    rows = cur.execute(q).fetchall()
sqlite3.OperationalError: table request_truncated already exists
  > Processed 'queries/histograms.sql' in 0 s.
0003: analyzing
Analyzing: /root/current-deployment-data/experiment-output/0003
  > Loading trace into database...
python3 scripts/analyze/load-logs.py /root/current-deployment-data/experiment-output/0003/eventDB.sqlite /root/current-deployment-data/experiment-output/0003/slave-*/*.trc
    Events loaded: 54807
  > Loaded trace into database in 0 s.
  > Running queries on trace database: queries/ethereum.sql
  > Processed 'queries/ethereum.sql' in 0 s.
  > Running queries on trace database: queries/aggregates.sql
  > Processed 'queries/aggregates.sql' in 0 s.
  > Running queries on trace database: queries/histograms.sql
Traceback (most recent call last):
  File "/root/scripts/analyze/run-queries.py", line 67, in <module>
    rows = cur.execute(q).fetchall()
sqlite3.OperationalError: table request_truncated already exists
  > Processed 'queries/histograms.sql' in 0 s.
0004: analyzing
Analyzing: /root/current-deployment-data/experiment-output/0004
  > Loading trace into database...
python3 scripts/analyze/load-logs.py /root/current-deployment-data/experiment-output/0004/eventDB.sqlite /root/current-deployment-data/experiment-output/0004/slave-*/*.trc
    Events loaded: 54857
  > Loaded trace into database in 0 s.
  > Running queries on trace database: queries/ethereum.sql
  > Processed 'queries/ethereum.sql' in 0 s.
  > Running queries on trace database: queries/aggregates.sql
  > Processed 'queries/aggregates.sql' in 0 s.
  > Running queries on trace database: queries/histograms.sql
Traceback (most recent call last):
  File "/root/scripts/analyze/run-queries.py", line 67, in <module>
    rows = cur.execute(q).fetchall()
sqlite3.OperationalError: table request_truncated already exists
  > Processed 'queries/histograms.sql' in 0 s.
0005: analyzing
Analyzing: /root/current-deployment-data/experiment-output/0005
  > Loading trace into database...
python3 scripts/analyze/load-logs.py /root/current-deployment-data/experiment-output/0005/eventDB.sqlite /root/current-deployment-data/experiment-output/0005/slave-*/*.trc
    Events loaded: 93225
  > Loaded trace into database in 0 s.
  > Running queries on trace database: queries/ethereum.sql
  > Processed 'queries/ethereum.sql' in 0 s.
  > Running queries on trace database: queries/aggregates.sql
  > Processed 'queries/aggregates.sql' in 0 s.
  > Running queries on trace database: queries/histograms.sql
Traceback (most recent call last):
  File "/root/scripts/analyze/run-queries.py", line 67, in <module>
    rows = cur.execute(q).fetchall()
sqlite3.OperationalError: table request_truncated already exists
  > Processed 'queries/histograms.sql' in 0 s.
0006: analyzing
Analyzing: /root/current-deployment-data/experiment-output/0006
  > Loading trace into database...
python3 scripts/analyze/load-logs.py /root/current-deployment-data/experiment-output/0006/eventDB.sqlite /root/current-deployment-data/experiment-output/0006/slave-*/*.trc
    Events loaded: 93204
  > Loaded trace into database in 0 s.
  > Running queries on trace database: queries/ethereum.sql
  > Processed 'queries/ethereum.sql' in 0 s.
  > Running queries on trace database: queries/aggregates.sql
  > Processed 'queries/aggregates.sql' in 0 s.
  > Running queries on trace database: queries/histograms.sql
Traceback (most recent call last):
  File "/root/scripts/analyze/run-queries.py", line 67, in <module>
    rows = cur.execute(q).fetchall()
sqlite3.OperationalError: table request_truncated already exists
  > Processed 'queries/histograms.sql' in 0 s.
0007: analyzing
Analyzing: /root/current-deployment-data/experiment-output/0007
  > Loading trace into database...
python3 scripts/analyze/load-logs.py /root/current-deployment-data/experiment-output/0007/eventDB.sqlite /root/current-deployment-data/experiment-output/0007/slave-*/*.trc
    Events loaded: 93209
  > Loaded trace into database in 0 s.
  > Running queries on trace database: queries/ethereum.sql
  > Processed 'queries/ethereum.sql' in 0 s.
  > Running queries on trace database: queries/aggregates.sql
  > Processed 'queries/aggregates.sql' in 0 s.
  > Running queries on trace database: queries/histograms.sql
Traceback (most recent call last):
  File "/root/scripts/analyze/run-queries.py", line 67, in <module>
    rows = cur.execute(q).fetchall()
sqlite3.OperationalError: table request_truncated already exists
  > Processed 'queries/histograms.sql' in 0 s.
0008: analyzing
Analyzing: /root/current-deployment-data/experiment-output/0008
  > Loading trace into database...
python3 scripts/analyze/load-logs.py /root/current-deployment-data/experiment-output/0008/eventDB.sqlite /root/current-deployment-data/experiment-output/0008/slave-*/*.trc
    Events loaded: 93210
  > Loaded trace into database in 0 s.
  > Running queries on trace database: queries/ethereum.sql
  > Processed 'queries/ethereum.sql' in 0 s.
  > Running queries on trace database: queries/aggregates.sql
  > Processed 'queries/aggregates.sql' in 0 s.
  > Running queries on trace database: queries/histograms.sql
Traceback (most recent call last):
  File "/root/scripts/analyze/run-queries.py", line 67, in <module>
    rows = cur.execute(q).fetchall()
sqlite3.OperationalError: table request_truncated already exists
  > Processed 'queries/histograms.sql' in 0 s.
0009: analyzing
Analyzing: /root/current-deployment-data/experiment-output/0009
  > Loading trace into database...
python3 scripts/analyze/load-logs.py /root/current-deployment-data/experiment-output/0009/eventDB.sqlite /root/current-deployment-data/experiment-output/0009/slave-*/*.trc
    Events loaded: 93226
  > Loaded trace into database in 0 s.
  > Running queries on trace database: queries/ethereum.sql
  > Processed 'queries/ethereum.sql' in 0 s.
  > Running queries on trace database: queries/aggregates.sql
  > Processed 'queries/aggregates.sql' in 0 s.
  > Running queries on trace database: queries/histograms.sql
Traceback (most recent call last):
  File "/root/scripts/analyze/run-queries.py", line 67, in <module>
    rows = cur.execute(q).fetchall()
sqlite3.OperationalError: table request_truncated already exists
  > Processed 'queries/histograms.sql' in 0 s.
0010: analyzing
Analyzing: /root/current-deployment-data/experiment-output/0010
  > Loading trace into database...
python3 scripts/analyze/load-logs.py /root/current-deployment-data/experiment-output/0010/eventDB.sqlite /root/current-deployment-data/experiment-output/0010/slave-*/*.trc
    Events loaded: 129116
  > Loaded trace into database in 0 s.
  > Running queries on trace database: queries/ethereum.sql
  > Processed 'queries/ethereum.sql' in 0 s.
  > Running queries on trace database: queries/aggregates.sql
  > Processed 'queries/aggregates.sql' in 0 s.
  > Running queries on trace database: queries/histograms.sql
Traceback (most recent call last):
  File "/root/scripts/analyze/run-queries.py", line 67, in <module>
    rows = cur.execute(q).fetchall()
sqlite3.OperationalError: table request_truncated already exists
  > Processed 'queries/histograms.sql' in 0 s.
0011: analyzing
Analyzing: /root/current-deployment-data/experiment-output/0011
  > Loading trace into database...
python3 scripts/analyze/load-logs.py /root/current-deployment-data/experiment-output/0011/eventDB.sqlite /root/current-deployment-data/experiment-output/0011/slave-*/*.trc
    Events loaded: 129595
  > Loaded trace into database in 0 s.
  > Running queries on trace database: queries/ethereum.sql
  > Processed 'queries/ethereum.sql' in 0 s.
  > Running queries on trace database: queries/aggregates.sql
  > Processed 'queries/aggregates.sql' in 0 s.
  > Running queries on trace database: queries/histograms.sql
Traceback (most recent call last):
  File "/root/scripts/analyze/run-queries.py", line 67, in <module>
    rows = cur.execute(q).fetchall()
sqlite3.OperationalError: table request_truncated already exists
  > Processed 'queries/histograms.sql' in 0 s.
0012: analyzing
Analyzing: /root/current-deployment-data/experiment-output/0012
  > Loading trace into database...
python3 scripts/analyze/load-logs.py /root/current-deployment-data/experiment-output/0012/eventDB.sqlite /root/current-deployment-data/experiment-output/0012/slave-*/*.trc
    Events loaded: 129338
  > Loaded trace into database in 0 s.
  > Running queries on trace database: queries/ethereum.sql
  > Processed 'queries/ethereum.sql' in 0 s.
  > Running queries on trace database: queries/aggregates.sql
  > Processed 'queries/aggregates.sql' in 0 s.
  > Running queries on trace database: queries/histograms.sql
Traceback (most recent call last):
  File "/root/scripts/analyze/run-queries.py", line 67, in <module>
    rows = cur.execute(q).fetchall()
sqlite3.OperationalError: table request_truncated already exists
  > Processed 'queries/histograms.sql' in 0 s.
0013: analyzing
Analyzing: /root/current-deployment-data/experiment-output/0013
  > Loading trace into database...
python3 scripts/analyze/load-logs.py /root/current-deployment-data/experiment-output/0013/eventDB.sqlite /root/current-deployment-data/experiment-output/0013/slave-*/*.trc
    Events loaded: 130256
  > Loaded trace into database in 0 s.
  > Running queries on trace database: queries/ethereum.sql
  > Processed 'queries/ethereum.sql' in 0 s.
  > Running queries on trace database: queries/aggregates.sql
  > Processed 'queries/aggregates.sql' in 0 s.
  > Running queries on trace database: queries/histograms.sql
Traceback (most recent call last):
  File "/root/scripts/analyze/run-queries.py", line 67, in <module>
    rows = cur.execute(q).fetchall()
sqlite3.OperationalError: table request_truncated already exists
  > Processed 'queries/histograms.sql' in 0 s.
0014: analyzing
Analyzing: /root/current-deployment-data/experiment-output/0014
  > Loading trace into database...
python3 scripts/analyze/load-logs.py /root/current-deployment-data/experiment-output/0014/eventDB.sqlite /root/current-deployment-data/experiment-output/0014/slave-*/*.trc
    Events loaded: 129401
  > Loaded trace into database in 0 s.
  > Running queries on trace database: queries/ethereum.sql
  > Processed 'queries/ethereum.sql' in 0 s.
  > Running queries on trace database: queries/aggregates.sql
  > Processed 'queries/aggregates.sql' in 0 s.
  > Running queries on trace database: queries/histograms.sql
Traceback (most recent call last):
  File "/root/scripts/analyze/run-queries.py", line 67, in <module>
    rows = cur.execute(q).fetchall()
sqlite3.OperationalError: table request_truncated already exists
  > Processed 'queries/histograms.sql' in 0 s.
0015: analyzing
Analyzing: /root/current-deployment-data/experiment-output/0015
  > Loading trace into database...
python3 scripts/analyze/load-logs.py /root/current-deployment-data/experiment-output/0015/eventDB.sqlite /root/current-deployment-data/experiment-output/0015/slave-*/*.trc
    Events loaded: 168665
  > Loaded trace into database in 0 s.
  > Running queries on trace database: queries/ethereum.sql
  > Processed 'queries/ethereum.sql' in 0 s.
  > Running queries on trace database: queries/aggregates.sql
  > Processed 'queries/aggregates.sql' in 1 s.
  > Running queries on trace database: queries/histograms.sql
Traceback (most recent call last):
  File "/root/scripts/analyze/run-queries.py", line 67, in <module>
    rows = cur.execute(q).fetchall()
sqlite3.OperationalError: table request_truncated already exists
  > Processed 'queries/histograms.sql' in 0 s.
0016: analyzing
Analyzing: /root/current-deployment-data/experiment-output/0016
  > Loading trace into database...
python3 scripts/analyze/load-logs.py /root/current-deployment-data/experiment-output/0016/eventDB.sqlite /root/current-deployment-data/experiment-output/0016/slave-*/*.trc
    Events loaded: 168466
  > Loaded trace into database in 0 s.
  > Running queries on trace database: queries/ethereum.sql
  > Processed 'queries/ethereum.sql' in 0 s.
  > Running queries on trace database: queries/aggregates.sql
  > Processed 'queries/aggregates.sql' in 1 s.
  > Running queries on trace database: queries/histograms.sql
Traceback (most recent call last):
  File "/root/scripts/analyze/run-queries.py", line 67, in <module>
    rows = cur.execute(q).fetchall()
sqlite3.OperationalError: table request_truncated already exists
  > Processed 'queries/histograms.sql' in 0 s.
0017: analyzing
Analyzing: /root/current-deployment-data/experiment-output/0017
  > Loading trace into database...
python3 scripts/analyze/load-logs.py /root/current-deployment-data/experiment-output/0017/eventDB.sqlite /root/current-deployment-data/experiment-output/0017/slave-*/*.trc
    Events loaded: 168726
  > Loaded trace into database in 0 s.
  > Running queries on trace database: queries/ethereum.sql
  > Processed 'queries/ethereum.sql' in 0 s.
  > Running queries on trace database: queries/aggregates.sql
  > Processed 'queries/aggregates.sql' in 1 s.
  > Running queries on trace database: queries/histograms.sql
Traceback (most recent call last):
  File "/root/scripts/analyze/run-queries.py", line 67, in <module>
    rows = cur.execute(q).fetchall()
sqlite3.OperationalError: table request_truncated already exists
  > Processed 'queries/histograms.sql' in 0 s.
0018: analyzing
Analyzing: /root/current-deployment-data/experiment-output/0018
  > Loading trace into database...
python3 scripts/analyze/load-logs.py /root/current-deployment-data/experiment-output/0018/eventDB.sqlite /root/current-deployment-data/experiment-output/0018/slave-*/*.trc
    Events loaded: 168390
  > Loaded trace into database in 0 s.
  > Running queries on trace database: queries/ethereum.sql
  > Processed 'queries/ethereum.sql' in 0 s.
  > Running queries on trace database: queries/aggregates.sql
  > Processed 'queries/aggregates.sql' in 1 s.
  > Running queries on trace database: queries/histograms.sql
Traceback (most recent call last):
  File "/root/scripts/analyze/run-queries.py", line 67, in <module>
    rows = cur.execute(q).fetchall()
sqlite3.OperationalError: table request_truncated already exists
  > Processed 'queries/histograms.sql' in 0 s.
0019: analyzing
Analyzing: /root/current-deployment-data/experiment-output/0019
  > Loading trace into database...
python3 scripts/analyze/load-logs.py /root/current-deployment-data/experiment-output/0019/eventDB.sqlite /root/current-deployment-data/experiment-output/0019/slave-*/*.trc
    Events loaded: 168875
  > Loaded trace into database in 0 s.
  > Running queries on trace database: queries/ethereum.sql
  > Processed 'queries/ethereum.sql' in 0 s.
  > Running queries on trace database: queries/aggregates.sql
  > Processed 'queries/aggregates.sql' in 1 s.
  > Running queries on trace database: queries/histograms.sql
Traceback (most recent call last):
  File "/root/scripts/analyze/run-queries.py", line 67, in <module>
    rows = cur.execute(q).fetchall()
sqlite3.OperationalError: table request_truncated already exists
  > Processed 'queries/histograms.sql' in 0 s.
0020: analyzing
Analyzing: /root/current-deployment-data/experiment-output/0020
  > Loading trace into database...
python3 scripts/analyze/load-logs.py /root/current-deployment-data/experiment-output/0020/eventDB.sqlite /root/current-deployment-data/experiment-output/0020/slave-*/*.trc
    Events loaded: 204326
  > Loaded trace into database in 1 s.
  > Running queries on trace database: queries/ethereum.sql
  > Processed 'queries/ethereum.sql' in 0 s.
  > Running queries on trace database: queries/aggregates.sql
  > Processed 'queries/aggregates.sql' in 1 s.
  > Running queries on trace database: queries/histograms.sql
Traceback (most recent call last):
  File "/root/scripts/analyze/run-queries.py", line 67, in <module>
    rows = cur.execute(q).fetchall()
sqlite3.OperationalError: table request_truncated already exists
  > Processed 'queries/histograms.sql' in 0 s.
0021: analyzing
Analyzing: /root/current-deployment-data/experiment-output/0021
  > Loading trace into database...
python3 scripts/analyze/load-logs.py /root/current-deployment-data/experiment-output/0021/eventDB.sqlite /root/current-deployment-data/experiment-output/0021/slave-*/*.trc
    Events loaded: 204493
  > Loaded trace into database in 0 s.
  > Running queries on trace database: queries/ethereum.sql
  > Processed 'queries/ethereum.sql' in 0 s.
  > Running queries on trace database: queries/aggregates.sql
  > Processed 'queries/aggregates.sql' in 1 s.
  > Running queries on trace database: queries/histograms.sql
Traceback (most recent call last):
  File "/root/scripts/analyze/run-queries.py", line 67, in <module>
    rows = cur.execute(q).fetchall()
sqlite3.OperationalError: table request_truncated already exists
  > Processed 'queries/histograms.sql' in 0 s.
0022: analyzing
Analyzing: /root/current-deployment-data/experiment-output/0022
  > Loading trace into database...
python3 scripts/analyze/load-logs.py /root/current-deployment-data/experiment-output/0022/eventDB.sqlite /root/current-deployment-data/experiment-output/0022/slave-*/*.trc
    Events loaded: 204480
  > Loaded trace into database in 0 s.
  > Running queries on trace database: queries/ethereum.sql
  > Processed 'queries/ethereum.sql' in 0 s.
  > Running queries on trace database: queries/aggregates.sql
  > Processed 'queries/aggregates.sql' in 1 s.
  > Running queries on trace database: queries/histograms.sql
Traceback (most recent call last):
  File "/root/scripts/analyze/run-queries.py", line 67, in <module>
    rows = cur.execute(q).fetchall()
sqlite3.OperationalError: table request_truncated already exists
  > Processed 'queries/histograms.sql' in 0 s.
0023: analyzing
Analyzing: /root/current-deployment-data/experiment-output/0023
  > Loading trace into database...
python3 scripts/analyze/load-logs.py /root/current-deployment-data/experiment-output/0023/eventDB.sqlite /root/current-deployment-data/experiment-output/0023/slave-*/*.trc
    Events loaded: 204568
  > Loaded trace into database in 1 s.
  > Running queries on trace database: queries/ethereum.sql
  > Processed 'queries/ethereum.sql' in 0 s.
  > Running queries on trace database: queries/aggregates.sql
  > Processed 'queries/aggregates.sql' in 1 s.
  > Running queries on trace database: queries/histograms.sql
Traceback (most recent call last):
  File "/root/scripts/analyze/run-queries.py", line 67, in <module>
    rows = cur.execute(q).fetchall()
sqlite3.OperationalError: table request_truncated already exists
  > Processed 'queries/histograms.sql' in 0 s.
0024: analyzing
Analyzing: /root/current-deployment-data/experiment-output/0024
  > Loading trace into database...
python3 scripts/analyze/load-logs.py /root/current-deployment-data/experiment-output/0024/eventDB.sqlite /root/current-deployment-data/experiment-output/0024/slave-*/*.trc
    Events loaded: 204447
  > Loaded trace into database in 0 s.
  > Running queries on trace database: queries/ethereum.sql
  > Processed 'queries/ethereum.sql' in 0 s.
  > Running queries on trace database: queries/aggregates.sql
  > Processed 'queries/aggregates.sql' in 1 s.
  > Running queries on trace database: queries/histograms.sql
Traceback (most recent call last):
  File "/root/scripts/analyze/run-queries.py", line 67, in <module>
    rows = cur.execute(q).fetchall()
sqlite3.OperationalError: table request_truncated already exists
  > Processed 'queries/histograms.sql' in 0 s.
0025: analyzing
Analyzing: /root/current-deployment-data/experiment-output/0025
  > Loading trace into database...
python3 scripts/analyze/load-logs.py /root/current-deployment-data/experiment-output/0025/eventDB.sqlite /root/current-deployment-data/experiment-output/0025/slave-*/*.trc
    Events loaded: 243628
  > Loaded trace into database in 1 s.
  > Running queries on trace database: queries/ethereum.sql
  > Processed 'queries/ethereum.sql' in 0 s.
  > Running queries on trace database: queries/aggregates.sql
  > Processed 'queries/aggregates.sql' in 1 s.
  > Running queries on trace database: queries/histograms.sql
Traceback (most recent call last):
  File "/root/scripts/analyze/run-queries.py", line 67, in <module>
    rows = cur.execute(q).fetchall()
sqlite3.OperationalError: table request_truncated already exists
  > Processed 'queries/histograms.sql' in 0 s.
0026: analyzing
Analyzing: /root/current-deployment-data/experiment-output/0026
  > Loading trace into database...
python3 scripts/analyze/load-logs.py /root/current-deployment-data/experiment-output/0026/eventDB.sqlite /root/current-deployment-data/experiment-output/0026/slave-*/*.trc
    Events loaded: 243974
  > Loaded trace into database in 1 s.
  > Running queries on trace database: queries/ethereum.sql
  > Processed 'queries/ethereum.sql' in 0 s.
  > Running queries on trace database: queries/aggregates.sql
  > Processed 'queries/aggregates.sql' in 1 s.
  > Running queries on trace database: queries/histograms.sql
Traceback (most recent call last):
  File "/root/scripts/analyze/run-queries.py", line 67, in <module>
    rows = cur.execute(q).fetchall()
sqlite3.OperationalError: table request_truncated already exists
  > Processed 'queries/histograms.sql' in 0 s.
0027: analyzing
Analyzing: /root/current-deployment-data/experiment-output/0027
  > Loading trace into database...
python3 scripts/analyze/load-logs.py /root/current-deployment-data/experiment-output/0027/eventDB.sqlite /root/current-deployment-data/experiment-output/0027/slave-*/*.trc
    Events loaded: 243821
  > Loaded trace into database in 1 s.
  > Running queries on trace database: queries/ethereum.sql
  > Processed 'queries/ethereum.sql' in 0 s.
  > Running queries on trace database: queries/aggregates.sql
  > Processed 'queries/aggregates.sql' in 1 s.
  > Running queries on trace database: queries/histograms.sql
Traceback (most recent call last):
  File "/root/scripts/analyze/run-queries.py", line 67, in <module>
    rows = cur.execute(q).fetchall()
sqlite3.OperationalError: table request_truncated already exists
  > Processed 'queries/histograms.sql' in 0 s.
0028: analyzing
Analyzing: /root/current-deployment-data/experiment-output/0028
  > Loading trace into database...
python3 scripts/analyze/load-logs.py /root/current-deployment-data/experiment-output/0028/eventDB.sqlite /root/current-deployment-data/experiment-output/0028/slave-*/*.trc
    Events loaded: 243806
  > Loaded trace into database in 1 s.
  > Running queries on trace database: queries/ethereum.sql
  > Processed 'queries/ethereum.sql' in 0 s.
  > Running queries on trace database: queries/aggregates.sql
  > Processed 'queries/aggregates.sql' in 1 s.
  > Running queries on trace database: queries/histograms.sql
Traceback (most recent call last):
  File "/root/scripts/analyze/run-queries.py", line 67, in <module>
    rows = cur.execute(q).fetchall()
sqlite3.OperationalError: table request_truncated already exists
  > Processed 'queries/histograms.sql' in 0 s.
0029: analyzing
Analyzing: /root/current-deployment-data/experiment-output/0029
  > Loading trace into database...
python3 scripts/analyze/load-logs.py /root/current-deployment-data/experiment-output/0029/eventDB.sqlite /root/current-deployment-data/experiment-output/0029/slave-*/*.trc
    Events loaded: 243855
  > Loaded trace into database in 1 s.
  > Running queries on trace database: queries/ethereum.sql
  > Processed 'queries/ethereum.sql' in 0 s.
  > Running queries on trace database: queries/aggregates.sql
  > Processed 'queries/aggregates.sql' in 1 s.
  > Running queries on trace database: queries/histograms.sql
Traceback (most recent call last):
  File "/root/scripts/analyze/run-queries.py", line 67, in <module>
    rows = cur.execute(q).fetchall()
sqlite3.OperationalError: table request_truncated already exists
  > Processed 'queries/histograms.sql' in 0 s.
0030: analyzing
Analyzing: /root/current-deployment-data/experiment-output/0030
  > Loading trace into database...
python3 scripts/analyze/load-logs.py /root/current-deployment-data/experiment-output/0030/eventDB.sqlite /root/current-deployment-data/experiment-output/0030/slave-*/*.trc
    Events loaded: 280902
  > Loaded trace into database in 1 s.
  > Running queries on trace database: queries/ethereum.sql
  > Processed 'queries/ethereum.sql' in 0 s.
  > Running queries on trace database: queries/aggregates.sql
  > Processed 'queries/aggregates.sql' in 1 s.
  > Running queries on trace database: queries/histograms.sql
Traceback (most recent call last):
  File "/root/scripts/analyze/run-queries.py", line 67, in <module>
    rows = cur.execute(q).fetchall()
sqlite3.OperationalError: table request_truncated already exists
  > Processed 'queries/histograms.sql' in 0 s.
0031: analyzing
Analyzing: /root/current-deployment-data/experiment-output/0031
  > Loading trace into database...
python3 scripts/analyze/load-logs.py /root/current-deployment-data/experiment-output/0031/eventDB.sqlite /root/current-deployment-data/experiment-output/0031/slave-*/*.trc
    Events loaded: 281493
  > Loaded trace into database in 1 s.
  > Running queries on trace database: queries/ethereum.sql
  > Processed 'queries/ethereum.sql' in 0 s.
  > Running queries on trace database: queries/aggregates.sql
  > Processed 'queries/aggregates.sql' in 1 s.
  > Running queries on trace database: queries/histograms.sql
Traceback (most recent call last):
  File "/root/scripts/analyze/run-queries.py", line 67, in <module>
    rows = cur.execute(q).fetchall()
sqlite3.OperationalError: table request_truncated already exists
  > Processed 'queries/histograms.sql' in 0 s.
0032: analyzing
Analyzing: /root/current-deployment-data/experiment-output/0032
  > Loading trace into database...
python3 scripts/analyze/load-logs.py /root/current-deployment-data/experiment-output/0032/eventDB.sqlite /root/current-deployment-data/experiment-output/0032/slave-*/*.trc
    Events loaded: 281227
  > Loaded trace into database in 1 s.
  > Running queries on trace database: queries/ethereum.sql
  > Processed 'queries/ethereum.sql' in 0 s.
  > Running queries on trace database: queries/aggregates.sql
  > Processed 'queries/aggregates.sql' in 1 s.
  > Running queries on trace database: queries/histograms.sql
Traceback (most recent call last):
  File "/root/scripts/analyze/run-queries.py", line 67, in <module>
    rows = cur.execute(q).fetchall()
sqlite3.OperationalError: table request_truncated already exists
  > Processed 'queries/histograms.sql' in 0 s.
0033: analyzing
Analyzing: /root/current-deployment-data/experiment-output/0033
  > Loading trace into database...
python3 scripts/analyze/load-logs.py /root/current-deployment-data/experiment-output/0033/eventDB.sqlite /root/current-deployment-data/experiment-output/0033/slave-*/*.trc
    Events loaded: 281161
  > Loaded trace into database in 1 s.
  > Running queries on trace database: queries/ethereum.sql
  > Processed 'queries/ethereum.sql' in 0 s.
  > Running queries on trace database: queries/aggregates.sql
  > Processed 'queries/aggregates.sql' in 1 s.
  > Running queries on trace database: queries/histograms.sql
Traceback (most recent call last):
  File "/root/scripts/analyze/run-queries.py", line 67, in <module>
    rows = cur.execute(q).fetchall()
sqlite3.OperationalError: table request_truncated already exists
  > Processed 'queries/histograms.sql' in 0 s.
0034: analyzing
Analyzing: /root/current-deployment-data/experiment-output/0034
  > Loading trace into database...
python3 scripts/analyze/load-logs.py /root/current-deployment-data/experiment-output/0034/eventDB.sqlite /root/current-deployment-data/experiment-output/0034/slave-*/*.trc
    Events loaded: 281293
  > Loaded trace into database in 1 s.
  > Running queries on trace database: queries/ethereum.sql
  > Processed 'queries/ethereum.sql' in 0 s.
  > Running queries on trace database: queries/aggregates.sql
  > Processed 'queries/aggregates.sql' in 1 s.
  > Running queries on trace database: queries/histograms.sql
Traceback (most recent call last):
  File "/root/scripts/analyze/run-queries.py", line 67, in <module>
    rows = cur.execute(q).fetchall()
sqlite3.OperationalError: table request_truncated already exists
  > Processed 'queries/histograms.sql' in 0 s.
0035: analyzing
Analyzing: /root/current-deployment-data/experiment-output/0035
  > Loading trace into database...
python3 scripts/analyze/load-logs.py /root/current-deployment-data/experiment-output/0035/eventDB.sqlite /root/current-deployment-data/experiment-output/0035/slave-*/*.trc
    Events loaded: 320555
  > Loaded trace into database in 1 s.
  > Running queries on trace database: queries/ethereum.sql
  > Processed 'queries/ethereum.sql' in 0 s.
  > Running queries on trace database: queries/aggregates.sql
  > Processed 'queries/aggregates.sql' in 2 s.
  > Running queries on trace database: queries/histograms.sql
Traceback (most recent call last):
  File "/root/scripts/analyze/run-queries.py", line 67, in <module>
    rows = cur.execute(q).fetchall()
sqlite3.OperationalError: table request_truncated already exists
  > Processed 'queries/histograms.sql' in 0 s.
0036: analyzing
Analyzing: /root/current-deployment-data/experiment-output/0036
  > Loading trace into database...
python3 scripts/analyze/load-logs.py /root/current-deployment-data/experiment-output/0036/eventDB.sqlite /root/current-deployment-data/experiment-output/0036/slave-*/*.trc
    Events loaded: 320584
  > Loaded trace into database in 1 s.
  > Running queries on trace database: queries/ethereum.sql
  > Processed 'queries/ethereum.sql' in 0 s.
  > Running queries on trace database: queries/aggregates.sql
  > Processed 'queries/aggregates.sql' in 2 s.
  > Running queries on trace database: queries/histograms.sql
Traceback (most recent call last):
  File "/root/scripts/analyze/run-queries.py", line 67, in <module>
    rows = cur.execute(q).fetchall()
sqlite3.OperationalError: table request_truncated already exists
  > Processed 'queries/histograms.sql' in 0 s.
0037: analyzing
Analyzing: /root/current-deployment-data/experiment-output/0037
  > Loading trace into database...
python3 scripts/analyze/load-logs.py /root/current-deployment-data/experiment-output/0037/eventDB.sqlite /root/current-deployment-data/experiment-output/0037/slave-*/*.trc
    Events loaded: 320658
  > Loaded trace into database in 1 s.
  > Running queries on trace database: queries/ethereum.sql
  > Processed 'queries/ethereum.sql' in 0 s.
  > Running queries on trace database: queries/aggregates.sql
  > Processed 'queries/aggregates.sql' in 2 s.
  > Running queries on trace database: queries/histograms.sql
Traceback (most recent call last):
  File "/root/scripts/analyze/run-queries.py", line 67, in <module>
    rows = cur.execute(q).fetchall()
sqlite3.OperationalError: table request_truncated already exists
  > Processed 'queries/histograms.sql' in 0 s.
0038: analyzing
Analyzing: /root/current-deployment-data/experiment-output/0038
  > Loading trace into database...
python3 scripts/analyze/load-logs.py /root/current-deployment-data/experiment-output/0038/eventDB.sqlite /root/current-deployment-data/experiment-output/0038/slave-*/*.trc
    Events loaded: 320417
  > Loaded trace into database in 1 s.
  > Running queries on trace database: queries/ethereum.sql
  > Processed 'queries/ethereum.sql' in 0 s.
  > Running queries on trace database: queries/aggregates.sql
  > Processed 'queries/aggregates.sql' in 2 s.
  > Running queries on trace database: queries/histograms.sql
Traceback (most recent call last):
  File "/root/scripts/analyze/run-queries.py", line 67, in <module>
    rows = cur.execute(q).fetchall()
sqlite3.OperationalError: table request_truncated already exists
  > Processed 'queries/histograms.sql' in 0 s.
0039: analyzing
Analyzing: /root/current-deployment-data/experiment-output/0039
  > Loading trace into database...
python3 scripts/analyze/load-logs.py /root/current-deployment-data/experiment-output/0039/eventDB.sqlite /root/current-deployment-data/experiment-output/0039/slave-*/*.trc
    Events loaded: 320277
  > Loaded trace into database in 1 s.
  > Running queries on trace database: queries/ethereum.sql
  > Processed 'queries/ethereum.sql' in 0 s.
  > Running queries on trace database: queries/aggregates.sql
  > Processed 'queries/aggregates.sql' in 2 s.
  > Running queries on trace database: queries/histograms.sql
Traceback (most recent call last):
  File "/root/scripts/analyze/run-queries.py", line 67, in <module>
    rows = cur.execute(q).fetchall()
sqlite3.OperationalError: table request_truncated already exists
  > Processed 'queries/histograms.sql' in 0 s.
0040: analyzing
Analyzing: /root/current-deployment-data/experiment-output/0040
  > Loading trace into database...
python3 scripts/analyze/load-logs.py /root/current-deployment-data/experiment-output/0040/eventDB.sqlite /root/current-deployment-data/experiment-output/0040/slave-*/*.trc
    Events loaded: 356334
  > Loaded trace into database in 2 s.
  > Running queries on trace database: queries/ethereum.sql
  > Processed 'queries/ethereum.sql' in 0 s.
  > Running queries on trace database: queries/aggregates.sql
  > Processed 'queries/aggregates.sql' in 2 s.
  > Running queries on trace database: queries/histograms.sql
Traceback (most recent call last):
  File "/root/scripts/analyze/run-queries.py", line 67, in <module>
    rows = cur.execute(q).fetchall()
sqlite3.OperationalError: table request_truncated already exists
  > Processed 'queries/histograms.sql' in 0 s.
0041: analyzing
Analyzing: /root/current-deployment-data/experiment-output/0041
  > Loading trace into database...
python3 scripts/analyze/load-logs.py /root/current-deployment-data/experiment-output/0041/eventDB.sqlite /root/current-deployment-data/experiment-output/0041/slave-*/*.trc
    Events loaded: 355844
  > Loaded trace into database in 1 s.
  > Running queries on trace database: queries/ethereum.sql
  > Processed 'queries/ethereum.sql' in 0 s.
  > Running queries on trace database: queries/aggregates.sql
  > Processed 'queries/aggregates.sql' in 2 s.
  > Running queries on trace database: queries/histograms.sql
Traceback (most recent call last):
  File "/root/scripts/analyze/run-queries.py", line 67, in <module>
    rows = cur.execute(q).fetchall()
sqlite3.OperationalError: table request_truncated already exists
  > Processed 'queries/histograms.sql' in 0 s.
0042: analyzing
Analyzing: /root/current-deployment-data/experiment-output/0042
  > Loading trace into database...
python3 scripts/analyze/load-logs.py /root/current-deployment-data/experiment-output/0042/eventDB.sqlite /root/current-deployment-data/experiment-output/0042/slave-*/*.trc
    Events loaded: 356248
  > Loaded trace into database in 1 s.
  > Running queries on trace database: queries/ethereum.sql
  > Processed 'queries/ethereum.sql' in 0 s.
  > Running queries on trace database: queries/aggregates.sql
  > Processed 'queries/aggregates.sql' in 2 s.
  > Running queries on trace database: queries/histograms.sql
Traceback (most recent call last):
  File "/root/scripts/analyze/run-queries.py", line 67, in <module>
    rows = cur.execute(q).fetchall()
sqlite3.OperationalError: table request_truncated already exists
  > Processed 'queries/histograms.sql' in 0 s.
0043: analyzing
Analyzing: /root/current-deployment-data/experiment-output/0043
  > Loading trace into database...
python3 scripts/analyze/load-logs.py /root/current-deployment-data/experiment-output/0043/eventDB.sqlite /root/current-deployment-data/experiment-output/0043/slave-*/*.trc
    Events loaded: 355734
  > Loaded trace into database in 1 s.
  > Running queries on trace database: queries/ethereum.sql
  > Processed 'queries/ethereum.sql' in 0 s.
  > Running queries on trace database: queries/aggregates.sql
  > Processed 'queries/aggregates.sql' in 2 s.
  > Running queries on trace database: queries/histograms.sql
Traceback (most recent call last):
  File "/root/scripts/analyze/run-queries.py", line 67, in <module>
    rows = cur.execute(q).fetchall()
sqlite3.OperationalError: table request_truncated already exists
  > Processed 'queries/histograms.sql' in 0 s.
0044: analyzing
Analyzing: /root/current-deployment-data/experiment-output/0044
  > Loading trace into database...
python3 scripts/analyze/load-logs.py /root/current-deployment-data/experiment-output/0044/eventDB.sqlite /root/current-deployment-data/experiment-output/0044/slave-*/*.trc
    Events loaded: 356183
  > Loaded trace into database in 1 s.
  > Running queries on trace database: queries/ethereum.sql
  > Processed 'queries/ethereum.sql' in 0 s.
  > Running queries on trace database: queries/aggregates.sql
  > Processed 'queries/aggregates.sql' in 2 s.
  > Running queries on trace database: queries/histograms.sql
Traceback (most recent call last):
  File "/root/scripts/analyze/run-queries.py", line 67, in <module>
    rows = cur.execute(q).fetchall()
sqlite3.OperationalError: table request_truncated already exists
  > Processed 'queries/histograms.sql' in 0 s.
0045: analyzing
Analyzing: /root/current-deployment-data/experiment-output/0045
  > Loading trace into database...
python3 scripts/analyze/load-logs.py /root/current-deployment-data/experiment-output/0045/eventDB.sqlite /root/current-deployment-data/experiment-output/0045/slave-*/*.trc
    Events loaded: 395928
  > Loaded trace into database in 1 s.
  > Running queries on trace database: queries/ethereum.sql
  > Processed 'queries/ethereum.sql' in 0 s.
  > Running queries on trace database: queries/aggregates.sql
  > Processed 'queries/aggregates.sql' in 2 s.
  > Running queries on trace database: queries/histograms.sql
Traceback (most recent call last):
  File "/root/scripts/analyze/run-queries.py", line 67, in <module>
    rows = cur.execute(q).fetchall()
sqlite3.OperationalError: table request_truncated already exists
  > Processed 'queries/histograms.sql' in 0 s.
0046: analyzing
Analyzing: /root/current-deployment-data/experiment-output/0046
  > Loading trace into database...
python3 scripts/analyze/load-logs.py /root/current-deployment-data/experiment-output/0046/eventDB.sqlite /root/current-deployment-data/experiment-output/0046/slave-*/*.trc
    Events loaded: 396040
  > Loaded trace into database in 2 s.
  > Running queries on trace database: queries/ethereum.sql
  > Processed 'queries/ethereum.sql' in 0 s.
  > Running queries on trace database: queries/aggregates.sql
  > Processed 'queries/aggregates.sql' in 2 s.
  > Running queries on trace database: queries/histograms.sql
Traceback (most recent call last):
  File "/root/scripts/analyze/run-queries.py", line 67, in <module>
    rows = cur.execute(q).fetchall()
sqlite3.OperationalError: table request_truncated already exists
  > Processed 'queries/histograms.sql' in 0 s.
0047: analyzing
Analyzing: /root/current-deployment-data/experiment-output/0047
  > Loading trace into database...
python3 scripts/analyze/load-logs.py /root/current-deployment-data/experiment-output/0047/eventDB.sqlite /root/current-deployment-data/experiment-output/0047/slave-*/*.trc
    Events loaded: 396311
  > Loaded trace into database in 1 s.
  > Running queries on trace database: queries/ethereum.sql
  > Processed 'queries/ethereum.sql' in 0 s.
  > Running queries on trace database: queries/aggregates.sql
  > Processed 'queries/aggregates.sql' in 2 s.
  > Running queries on trace database: queries/histograms.sql
Traceback (most recent call last):
  File "/root/scripts/analyze/run-queries.py", line 67, in <module>
    rows = cur.execute(q).fetchall()
sqlite3.OperationalError: table request_truncated already exists
  > Processed 'queries/histograms.sql' in 0 s.
0048: analyzing
Analyzing: /root/current-deployment-data/experiment-output/0048
  > Loading trace into database...
python3 scripts/analyze/load-logs.py /root/current-deployment-data/experiment-output/0048/eventDB.sqlite /root/current-deployment-data/experiment-output/0048/slave-*/*.trc
    Events loaded: 395705
  > Loaded trace into database in 1 s.
  > Running queries on trace database: queries/ethereum.sql
  > Processed 'queries/ethereum.sql' in 0 s.
  > Running queries on trace database: queries/aggregates.sql
  > Processed 'queries/aggregates.sql' in 2 s.
  > Running queries on trace database: queries/histograms.sql
Traceback (most recent call last):
  File "/root/scripts/analyze/run-queries.py", line 67, in <module>
    rows = cur.execute(q).fetchall()
sqlite3.OperationalError: table request_truncated already exists
  > Processed 'queries/histograms.sql' in 0 s.
0049: analyzing
Analyzing: /root/current-deployment-data/experiment-output/0049
  > Loading trace into database...
python3 scripts/analyze/load-logs.py /root/current-deployment-data/experiment-output/0049/eventDB.sqlite /root/current-deployment-data/experiment-output/0049/slave-*/*.trc
Finished processing results. First unprocessed: 53
    Events loaded: 395895
  > Loaded trace into database in 1 s.
  > Running queries on trace database: queries/ethereum.sql
  > Processed 'queries/ethereum.sql' in 0 s.
  > Running queries on trace database: queries/aggregates.sql
Finished processing results. First unprocessed: 54
Finished processing results. First unprocessed: 55
Finished processing results. First unprocessed: 50
Finished processing results. First unprocessed: 56
  > Processed 'queries/aggregates.sql' in 2 s.
  > Running queries on trace database: queries/histograms.sql
Traceback (most recent call last):
  File "/root/scripts/analyze/run-queries.py", line 67, in <module>
    rows = cur.execute(q).fetchall()
sqlite3.OperationalError: table request_truncated already exists
  > Processed 'queries/histograms.sql' in 0 s.
Finished processing results. First unprocessed: 51
Finished processing results. First unprocessed: 52
Finished processing results. First unprocessed: 57
Finished continuous result analysis.
